FROM alpine:latest AS builder

# system dependencies
RUN apk add --no-cache \
    protobuf \
    protobuf-dev \
    protoc \
    make \
    go \
    libcap

ENV GOPATH=/root/go
ENV PATH="/root/go/bin:$PATH"
WORKDIR /usr/local/src

# code gen
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

# app dependencies
COPY go.mod go.sum ./
RUN go mod download

# build
COPY . .
RUN make proto && \
    go build -o octo-cdn ./cmd/octo-cdn && \
    setcap cap_net_bind_service=+ep ./octo-cdn

# runner
FROM alpine:latest

WORKDIR /opt/octo-cdn

RUN chown 1000:1000 /opt/octo-cdn

USER 1000

COPY --from=builder /usr/local/src/octo-cdn .

ENTRYPOINT ["./octo-cdn"]
