FROM alpine:latest AS builder

# system dependencies
RUN apk add --no-cache go

ENV GOPATH=/root/go
WORKDIR /usr/local/src

# app dependencies
COPY go.mod go.sum ./
RUN go mod download

# build
COPY . .
RUN go build -o auth-server ./cmd/auth-server

# runner
FROM alpine:latest

WORKDIR /opt/auth-server

RUN chown 1000:1000 /opt/auth-server

USER 1000

COPY --from=builder /usr/local/src/auth-server .

ENTRYPOINT ["./auth-server"]
